#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
xrandr --output eDP1 --rotate right --scale .6x.6

. /etc/X11/Xsession
